### ISSUE TITLE
[Member Dashboard] Build

### ISSUE THREAD

**Issue by crwallace** [colorofchange/TechTeam#55]
Must Include:
- [ ] Total Membership #48 
- [ ] Members by Race #49 
- [ ] Members by Gender #50 
- [ ] Members by Age #51 
- [ ] Members by Geography #52 
- [ ] Average length on the list #53 
- [ ] Change in last 30 days #54
